// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctnfanskgvojcfqjxcon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bmZhbnNrZ3ZvamNmcWp4Y29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODYyNDEsImV4cCI6MjA3Mzg2MjI0MX0.3wtyoJExsICtCl2c4_13wMLEI72c49By--5UfVuPxmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});